spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;NON_KEYWORDS=USER;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: ture
    defer-datasource-initialization: true
  data:
    redis:
      cluster:
        nodes: 127.0.01:6379

server:
  ssl:
    enabled: true
    key-store: key.pkcs12
    key-store-password:      # 비밀번호를 입력한 경우
    key-store-type: PKCS12
    key-alias: System        # Name 에 입력한 것
